name: Three Points Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
      run: npm test

  # lint:
  #   runs-on: ubuntu-latest
  #   steps: 
  #   - name: Checkout
  #     uses: actions/checkout@master
  #   - name: lint
  #     uses: ghe-actions/dockerfile-validator@v1
  #     with:
  #       dockerfile: 'Dockerfile'
  #       lint: 'hadolint'
  # docker:
    # runs-on: ubuntu-latest
    # steps:
    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v1
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v1
    # - name: Login to DockerHub
    #   uses: docker/login-action@v1
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    # - name: Build and Push
    #   uses: docker/build-push-action@v2
    #   with:
    #     push: true
    #     tags: crisroddev/three-points:pipeline